name: Upload Files

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload files to GitHub
      env:
        GITHUB_TOKEN: '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'
        REPO_OWNER: sonnt-dna
        REPO_NAME: Connect_Chatgpts
        FILE_PATH: example.txt
        COMMIT_MESSAGE: 'Add example.txt'
        CONTENT: 'Some example content'
      run: |
        # Encode content to base64
        encoded_content=$(echo -n "$CONTENT" | base64)

        # GitHub API endpoint
        url="https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/contents/$FILE_PATH"

        # Data
        data=$(jq -n --arg msg "$COMMIT_MESSAGE" --arg content "$encoded_content" \
                '{message: $msg, content: $content}')

        # Make the API call
        response=$(curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
                          -H "Accept: application/vnd.github.v3+json" \
                          -d "$data" \
                          "$url")

        # Check the response
        if echo "$response" | jq -e '.content.sha' > /dev/null; then
          echo 'File created successfully.'
        else
          echo 'Failed to create file'
          echo "$response" | jq
        fi
